apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "go-integration.fullname" . }}
  labels:
    app: {{ template "go-integration.name" . }}
    chart: {{ template "go-integration.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations: {}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "local-path"
  volumeName: ""
